version: '3'
services:
  slurm:
    image: giovtorres/docker-centos7-slurm:latest
    hostname: slurm
    command: tail -f /dev/null
    expose: 
      - "6817"
      - "6818"
      - "6819"
    volumes:
    - ./slurm/slurm_brain.conf:/etc/slurm/slurm.conf   
    - ./brain/job_submission_example:/root/job_submission_example
  wt:
    build: ./wt_centos
    hostname: wt
    #entrypoint: tail -f /dev/null
    depends_on:
     - slurm  
    volumes:
    - ./swebview:/sWebView   
    - ./slurm/slurm_brain.conf:/etc/slurm/slurm.conf   
    ports:
    - "8080:8080"
    links:
       - slurm
