# .bashrc

# User specific aliases and functions

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi


alias cmake='cmake3'
export TERM=xterm
source /opt/rh/devtoolset-7/enable
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/
